### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by B4RD4k** [rfunix/Pompem#12]
Hi,
Please add a version to python 3.5 :)

**Comment by rfunix** [comment]
Hi ,
I not understand your question, Pompem is running in python 3.5 version.
Thanks.

**Comment by eranvak** [comment]
Hi bro,
No Question, just a request to add support for python in 2.7 version if you can :)

10x

**Comment by rfunix** [comment]
Hi,
Ok, I understand. I will add support for python 2.7 as soon as possible.

Thanks for suggestion :)

**Comment by eranvak** [comment]
NP...
10x man appericiate it ;)

**Comment by blmvxer** [comment]
If you need help with porting to 2.7 I can help

**Comment by q2dg** [comment]
I think this request nowadays can be closed. Let's face the future
