### ISSUE TITLE
Place COPYING/LICENSE file

### ISSUE THREAD

**Issue by mboelen** [rfunix/Pompem#15]
Hi @rfunix,

Had to search for the license and couldn't find it in the tool itself, nor on GitHub. Until I finally saw it at the very end of the README.md. Would be great if you could place open source license in a file so it is also detected automatically by GitHub interface.

Thanks for your work!

**Comment by zeroxenator** [comment]
Hey, Can I take this?

**Comment by dmaroulidis** [comment]
Added LICENCE file on pr #19

**Comment by rfunix** [comment]
Hi @zeroxenator , @dmaroulidis solved this issue. Thanks anyway.
