### ISSUE TITLE
Erro de execução e na instalação dos requerimentos

### ISSUE THREAD

**Issue by maximozsec** [rfunix/Pompem#7]
Erro ao executar:
> [maximoz@maximoz Pompem-dev]$ python pompem.py 
  File "pompem.py", line 76
    """
      ^
SyntaxError: Missing parentheses in call to 'print'

Tentei editar mas não vi erro no código (bizarro)

Criei o virtualenv e tentei instalar os requerimentos com pip no arquivo requirements.txt mas:
> [maximoz@maximoz Pompem-dev]$ pip install -r requirements.txt
Collecting BeautifulSoup==3.2.1 (from -r requirements.txt (line 1))
  Using cached BeautifulSoup-3.2.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
     File "<string>", line 20, in <module
     ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-14bpa9_b/BeautifulSoup

Obs:. Uso distribuição baseada no Arch Linux.

**Comment by rfunix** [comment]
Qual a versão do Python que você está utilizando ?

Pompem works out of the box with Python version '''2.6.x''' and '''2.7.x''' on any platform.

**Comment by maximozsec** [comment]
To ligado. Eu tinha usado `python2 pompem.py` pra executar mas tinha dado erro do mesmo jeito. Mas vi aqui e o problema era que o pacote requests 2.2.1 no arquivo requirements.txt tem outro nome no sistema de pacotes do arch (python2-requests). Enfim, deu certo. Desculpe a issue inútil.

**Comment by rfunix** [comment]
Cara não é inútil, alguém pode ter esse problema.
Valeu pelo feedback.
